импорт object: 'NoneType' object has no attribute 'filepath'
PavelBlend/blender-xray pull request #117
Opened 2016-12-18 00:49 UTC by igelbox

(fix #114)

2016-12-19 12:33 UTC, PavelBlend commented
Проверил. Работает не так как нужно.

Пример:
Нужно создать объект с именем `test_object`, добавить ему материал `test_material`, добавить этому материалу текстуру с именем `terrain\terrain_escape`, а изображение не указывать. Потом этот объект нужно экспортировать в `test_object.object` с выключенной опцией `Texture Name from image path`. Экспорт пройдёт успешно, не смотря на отсутствие изображения в текстуре. Далее этот же `object` нужно импортировать в туже сцену.

В итоге импортируется:
Объект test_object.001.
Создастся новый материал test_material.001 (что и есть правильно).
И этому материалу добавится уже имеющаяся в сцене текстура terrain\terrain_escape (а это не правильно).

Нужно, чтобы не использовалась текстура `terrain\terrain_escape`, а создавалась новая, которая бы имела изображение (`Texture Folder` +`terrain\terrain_escape.dds`). Так как имеющаяся текстура не имеет изображения.

2017-01-04 19:58 UTC, PavelBlend requested changes
Теперь я понял одну проблему. Плагин создаст новую текстуру, если имеющаяся не будет иметь изображения. И имя созданной текстуры будет иметь в конце ".001". Экспорт объекта, содержащего материал с созданной текстурой, с выключенным параметром "Texture Name From Image Path" будет неправильным (путь к текстуре будет в конце содержать ".001").

Поэтому есть предложение:
сделать XRay свойство "Texture" в панели XRay вкладки Material. И использовать это свойство при экспорте. А текстуры будут иметь имя, совпадающее с путём текстуры только для удобства и для поиска идентичных текстур при импорте.

2017-01-04 21:17 UTC, igelbox commented
Что-то мне не нравится затея в новым свойством, т.к. не понятно что с ним делать, если пользователь выбрал другую картинку для текстуры.
Вижу 2 варианта:
1. Выводить warning при экспорте, если имя текстуры содержит `.цифры`.
2. Убрать настройку `Texture Name From Image Path`, пусть плагин ведёт себя так, как будто бы она всегда включена.

2017-01-04 21:37 UTC, PavelBlend commented
> Убрать настройку Texture Name From Image Path, пусть плагин ведёт себя так, как будто бы она всегда включена.

Я думаю её убирать не стоит. Так как иногда пути к текстурам могут сбиться. А при выключении этой опции не нужно искать файлы изображений. К примеру, у пользователя не будет распакованных архивов игры, но он точно знает, что в blend файле имена текстур были даны правильно (например, другой пользователь у себя на компьютере имена настраивал, имея распакованные архивы).

2017-01-06 07:42 UTC, igelbox commented
Вот мы и пришли от ошибки к исправлению странного поведения.
Я думаю, надо закрывать этот PR, т.к. он исправляет ошибку. А по поводу странного поведения, когда имя текстуры содержит `.цифры` - можно написать отдельную issue.

2017-01-14 01:11 UTC, merged