рандомные цвета материалов
PavelBlend/blender-xray pull request #118
Opened 2016-12-18 02:05 UTC by igelbox

(resolve #115)

2016-12-18 17:29 UTC, PavelBlend commented
Сломался импорт dm. Я использовал ImportContext из fmt_object_imp, чтобы не дублировать код.
Может перенести класс ImportContext в другой модуль и сделать его универсальным для любого формата?

Вот ошибка:

```Traceback (most recent call last):
  File "C:\Program Project\Blender Foundation\Blender 2.78a\2.78\scripts\addons\io_scene_xray\plugin.py", line 212, in execute
    bpy=bpy
TypeError: __init__() missing 1 required positional argument: 'color_materials'

location: <unknown location>:-1
```

2016-12-25 20:42 UTC, PavelBlend commented
Проверил. Всё равно все цвета материалов слишком контрастные. Нужно чтобы каждая составляющая (Красный Зелёный Синий) цвета была в пределах 0.2 ... 0.8.
Вот пример:
![colorize_materials](https://cloud.githubusercontent.com/assets/7983249/21472830/ac233d08-cafb-11e6-9bd9-55379df15206.png)

2017-01-02 22:02 UTC, igelbox commented
Я тут подумал, что расцветка материалов это вооще ни разу не опция импорта. Теперь это самостоятельный оператор.

2017-01-04 20:29 UTC, PavelBlend requested changes
Может заменить параметр Power на два параметра Min и Max?
И изменить способ установки цвета:
задавать не через HSV, а через RGB.

В итоге цвет материала будет:
Red = рандомная величина * (Max - Min) + Min
Green = рандомная величина * (Max - Min) + Min
Blue = рандомная величина * (Max - Min) + Min

2017-01-04 20:55 UTC, igelbox commented
Я так пробовал, получалось хуже:
- Min/Max - был сложнее в настройке, а радости мало было.
- RGB - выдавал много серых цветов, а HSV - позволяет ограничить минимальную насыщенность цвета.

2017-01-05 10:49 UTC, PavelBlend approved these changes
Тогда пусть остаётся всё, как есть.

2017-01-05 10:55 UTC, PavelBlend commented
Я теперь понял как работает параметр power. До этого не совсем было понятно. Чтобы получить цвета в диапазоне [0.2 ... 0.8] нужно ведь установить Power в 0.6? А для диапазона [0.4 ... 0.6] Power будет 0.4?

2017-01-05 19:35 UTC, igelbox commented
Проверил по формулам - да, если `power=0.6`, то `0.2..0.8`.
Но я над этим не заморачивался. Я делал так, чтобы для `power=0` - был серый цвет, а для `power=1` - максимально насыщенный.
Норм?

2017-01-05 22:42 UTC, merged