Experimental/support details slots
PavelBlend/blender-xray pull request #125
Opened 2017-01-07 21:52 UTC by PavelBlend

Реализована поддержка полного импорта/экспорта level.details

Поддерживается импорт/экспорт level.details из всех известных билдов (от 1096 до Зов Припяти).

Все данные слотов (освещение, тени, индексы, плотность мешей и т. д.) сохраняются в виде изображений.

2017-01-14 00:47 UTC, igelbox requested changes
И ещё по коду: очень не хватает тестов.

2017-01-14 00:47 UTC, igelbox commented on .gitignore
> +__pycache__
Не хватает перевода строки. Это порой бывает важно для сравнения версий в git-е.

2017-01-14 00:47 UTC, igelbox commented on io_scene_xray/__init__.py
> -    'name':     'XRay Engine Tools',
Лучше бы не править/форматировать файлы, которые на прямую не относятся к фиче, которую делаешь. Думаю, стоит вернуть как было раньше.

2017-01-14 00:47 UTC, igelbox commented on io_scene_xray/details/operators.py
> +    save_folder = bpy.props.StringProperty(name='Save Folder')
Похоже на экспорт при импорте, очень смущает.
Может лучше создавать их в системном каталоге для временных файлов, загружать в `image` или может есть способ сразу в Image пиксели проставлять?
А потом делать Image.pack() (чтобы картинка сохранилась в blend-файл)?

2017-01-14 00:47 UTC, igelbox commented on io_scene_xray/details/operators.py
> +            ('NEW', 'Builds 1569-CoP', ''),
ID-шники отличаются от enum-а в импорте. Может быть их можно унифицировать?

2017-01-14 00:47 UTC, igelbox commented on io_scene_xray/details/read.py
> +        del meshes_images_pixels
Зачем `del`? В Python же есть сборщик мусора.

2017-01-14 00:47 UTC, igelbox commented on io_scene_xray/details/types.py
> +            ('VERSION_3', 'New', 'level.details version 3 (builds 1569-CoP)'),
Опять новые идентификаторы для перечисления. Может быть их можно унифицировать?

2017-01-14 00:47 UTC, igelbox commented on io_scene_xray/details/write.py
> +            'Meshes Object "' + mo.name + '" has too many childrens: {0}. ' \
S-лишняя, т.к. children - уже множественное число.

2017-01-14 00:47 UTC, igelbox commented on io_scene_xray/details/write.py
> +                '" has incorrect children object type: {0}. ' \
В единственном числе будет - child.

2017-01-14 00:47 UTC, igelbox commented on io_scene_xray/details/write.py
> +            'Should be not more {1}.'.format(
Правильнее - not more than {1}

2017-01-14 00:47 UTC, igelbox commented on io_scene_xray/xray_inject.py
> +    detail = bpy.props.PointerProperty(type=XRayObjectDetailsProperties)
Просто заметка: значения свойств не загрузятся из файлов, сохранённых старой версией плагина.
Идея выноса свойств в подструктуру - хорошая.

2017-01-14 00:47 UTC, igelbox commented on io_scene_xray/xray_inject.py
> +    bpy.utils.register_class(XRayObjectDetailsProperties)
А кто будет unregister делать? Лучше бы просто добавить в общий список `classes` классов на регистрацию.

2017-01-14 00:47 UTC, igelbox commented on io_scene_xray/details/operators.py
> +        name='Lighting Old Format',
Как-то странно звучит, когда всегда "старый". Может просто убрать слово Old отсюда?

2017-01-17 09:45 UTC, PavelBlend commented
Я сделал unregister классов для details. И ещё выяснилось, что нету unregister для других классов. Я создам issues.

2017-01-17 10:00 UTC, PavelBlend commented
И ещё хотел сказать:
может создавать issues в моём форке? А то я уже не могу здесь найти некоторые сообщения. При добавлении новых коммитов сообщения удалились.

2017-01-17 19:54 UTC, igelbox commented
> может создавать issues в моём форке

Если ты надумаешь пилить свою самобытную версию плагина, то да. А если работать над этой, то только в этом репозитории. Обычно так делают.


> А то я уже не могу здесь найти некоторые сообщения

А какие они были или прочто они были?
Может они просто переехали жить в https://github.com/igelbox/blender-xray/issues?q=is%3Aissue+is%3Aclosed ?))

2017-01-17 20:00 UTC, PavelBlend commented
> А если работать над этой, то только в этом репозитории

А точно. В моём форке даже кнопки Issues нету.

> А какие они были или прочто они были?

Ты написал в самом коде комментарий, я создал новый коммит, который этот код изменил и твой комментарий пропал.

2017-01-17 20:07 UTC, igelbox commented
Я думаю, он пропал потому, что в каком-то коммите была изменена строка кода, к которой я коментарий писал.
Но, на самом деле, он не пропал. Я думаю, ты можешь найти все комментарии на этой странице (они просто схлопнутые) поищи текст "Show outdated".

2017-10-09 14:23 UTC, PavelBlend commented
А данный пулл не получиться смержить? Если нет, то что нужно изменить или сделать для этого?

2017-10-09 16:32 UTC, igelbox commented
@PavelBlend 
>А данный пулл не получиться смержить?

Получится, после доработки.

> Если нет, то что нужно изменить или сделать для этого?

Мне надо его его ещё раз посмотреть.
А пока, тестов, как минимум не хватает. Но ты лучше потренируйся пока тесты писать на #144, чтоб нам в этом огромном PR-е ещё большей беды не натворить.

2017-10-10 08:00 UTC, PavelBlend commented
Я записал видео, чтобы было легче понять, как импорт/экспорт работает:
[https://www.youtube.com/watch?v=u7Vyr02LiNE&feature=youtu.be](url)

2018-01-14 13:33 UTC, PavelBlend commented on .gitignore
> +__pycache__
Странно, почему этот комментарий не стал outdated. Я ведь добавлял новую строку в этот файл, но гитхаб видит только одну. Хотя их на самом деле две, если скачать и посмотреть в текстовом редакторе. Вот коммит d5c396675e35edcf44d50200962c103e2316e3e5

2018-01-14 13:46 UTC, PavelBlend commented on io_scene_xray/details/read.py
> +        del meshes_images_pixels
Я уже по-моему здесь писал, но не знаю где мой комментарий. Я экспериментировал и выяснил, что без del блендер использует больше памяти, чем с ним.

2018-01-15 16:27 UTC, igelbox commented on .gitignore
> +__pycache__
Да. Странно. Ну ОК, раз строка есть, то будем считать, что проблема решена.

2018-01-15 16:29 UTC, igelbox commented on io_scene_xray/details/read.py
> +        del meshes_images_pixels
Это очень странно.
Как проверить? Импортировать любой details-файл и посмотреть, какое потребление памяти сам Blender показывает?

2018-01-15 16:40 UTC, PavelBlend commented on io_scene_xray/details/read.py
> +        del meshes_images_pixels
Импортировал level.details из кордона ТЧ. Я смотрел в диспетчере задач процесс блендера. Потом удалил del и снова смотрел. В итоге без del памяти требовалось на сотни мегабайт больше.

2018-01-16 18:01 UTC, PavelBlend commented
@igelbox А мне как тесты писать? Нужно сначала смержить твою `develop` ветку в мою `experimental/support-details-slots`, а потом писать тесты? Чтобы они были актуальными, а не для устаревшей версии плагина.

2018-01-16 20:54 UTC, igelbox commented on io_scene_xray/details/convert.py
> +from ..utils import AppError
Вау, а я и не знал, что в python-е так импортировать можно. Спасибо, за идею.

2018-01-16 20:56 UTC, igelbox commented
> А мне как тесты писать? Нужно сначала смержить твою develop ветку в мою experimental/support-details-slots, а потом писать тесты?

@PavelBlend, да, смержить develop в твою ветку - я бы сказал, что это самая первостепенная задача (чтоб при исправлениях ты мог использовать актуальные/свежие версии общих модулей).

2018-01-18 13:37 UTC, PavelBlend commented on io_scene_xray/details/read.py
> +        del meshes_images_pixels
> Это очень странно.

мне кажется, что не странно. Так как я с помощью del удаляю большие списки сразу после того, как они не нужны, а не после завершения функции.

2018-01-18 18:50 UTC, igelbox commented on io_scene_xray/details/read.py
> +        del meshes_images_pixels
> удаляю большие списки сразу после того, как они не нужны

ОК. Пусть будет, раз "памяти требовалось на сотни мегабайт больше".

2018-01-23 15:59 UTC, PavelBlend commented
@igelbox , что ещё изменить/добавить, чтобы можно было мержить?

2018-01-23 18:35 UTC, igelbox commented
@PavelBlend 
> что ещё изменить/добавить, чтобы можно было мержить?

Codecov говорит, что:
> Merging #125 into develop will decrease coverage by 2.11%.

И нам лучше бы не понижать "градус" покрытия кода тестами. Но, для этого, столь многострадального PR-а, можно и допустить такое понижение.
Я посмотрю этот PR ещё разок.

2018-01-28 18:26 UTC, igelbox approved these changes

2018-01-28 19:24 UTC, merged