Фикс дублирующихся текстур при импорте object
PavelBlend/blender-xray pull request #172
Opened 2018-02-08 14:07 UTC by PavelBlend

См. #170

2018-02-19 06:41 UTC, igelbox requested changes
Теста очень не хватает.

2018-02-19 09:05 UTC, PavelBlend commented
Я хотел написать тесты, но перед написанием запустил уже имеющиеся и они почему-то сломаны. 6 fails:
```======================================================================
FAIL: test_import_separate_materials_with_different_cshader (tests.cases.test_fmt_object.TestFormatObject)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\git\blender-xray\tests\cases\test_fmt_object.py", line 97, in test_import_separate_materials_with_different_c
shader
    self._test_import_separate_materials(mat, tex)
  File "D:\git\blender-xray\tests\cases\test_fmt_object.py", line 145, in _test_import_separate_materials
    self.assertNotEqual(imported_texture, tex)
AssertionError: bpy.data.textures['eye'] == bpy.data.textures['eye']

======================================================================
FAIL: test_import_separate_materials_with_different_eshader (tests.cases.test_fmt_object.TestFormatObject)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\git\blender-xray\tests\cases\test_fmt_object.py", line 89, in test_import_separate_materials_with_different_e
shader
    self._test_import_separate_materials(mat, tex)
  File "D:\git\blender-xray\tests\cases\test_fmt_object.py", line 145, in _test_import_separate_materials
    self.assertNotEqual(imported_texture, tex)
AssertionError: bpy.data.textures['eye'] == bpy.data.textures['eye']

======================================================================
FAIL: test_import_separate_materials_with_different_flags (tests.cases.test_fmt_object.TestFormatObject)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\git\blender-xray\tests\cases\test_fmt_object.py", line 81, in test_import_separate_materials_with_different_f
lags
    self._test_import_separate_materials(mat, tex)
  File "D:\git\blender-xray\tests\cases\test_fmt_object.py", line 145, in _test_import_separate_materials
    self.assertNotEqual(imported_texture, tex)
AssertionError: bpy.data.textures['eye'] == bpy.data.textures['eye']

======================================================================
FAIL: test_import_separate_materials_with_different_gamemtl (tests.cases.test_fmt_object.TestFormatObject)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\git\blender-xray\tests\cases\test_fmt_object.py", line 105, in test_import_separate_materials_with_different_
gamemtl
    self._test_import_separate_materials(mat, tex)
  File "D:\git\blender-xray\tests\cases\test_fmt_object.py", line 145, in _test_import_separate_materials
    self.assertNotEqual(imported_texture, tex)
AssertionError: bpy.data.textures['eye'] == bpy.data.textures['eye']

======================================================================
FAIL: test_import_separate_materials_with_different_name (tests.cases.test_fmt_object.TestFormatObject)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\git\blender-xray\tests\cases\test_fmt_object.py", line 73, in test_import_separate_materials_with_different_n
ame
    self._test_import_separate_materials(mat, tex)
  File "D:\git\blender-xray\tests\cases\test_fmt_object.py", line 145, in _test_import_separate_materials
    self.assertNotEqual(imported_texture, tex)
AssertionError: bpy.data.textures['eye'] == bpy.data.textures['eye']

======================================================================
FAIL: test_import_separate_materials_with_different_vmap (tests.cases.test_fmt_object.TestFormatObject)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\git\blender-xray\tests\cases\test_fmt_object.py", line 113, in test_import_separate_materials_with_different_
vmap
    self._test_import_separate_materials(mat, tex)
  File "D:\git\blender-xray\tests\cases\test_fmt_object.py", line 145, in _test_import_separate_materials
    self.assertNotEqual(imported_texture, tex)
AssertionError: bpy.data.textures['eye'] == bpy.data.textures['eye']
```

Может эти тесты неправильные? Или я не правильно отредактировал ошибку?
И что делать? В этой ветке попробовать их починить или ты сам починишь?

2018-03-04 22:05 UTC, igelbox commented
@PavelBlend, да, ты прав, эти тесты были не правильные. Я их поправил в твоей ветке.
Получается, что теперишние правленные тесты уже покрывают твою новую логику => я уже не уверен, что тут ещё дополнительные тесты нужны. Но, если ты считаешь, что какую-то логику надо закрыть, то тест лишним не будет.

2018-03-04 22:05 UTC, igelbox approved these changes

2018-03-05 07:57 UTC, PavelBlend commented
Раз тесты покрывают мой код, то я тесты писать не буду. А если и буду, то в другой ветке, которые будут покрывать другой код.

2018-03-05 20:35 UTC, merged