Joint Limits в виде XRay свойств (вместо IK лимитов)
PavelBlend/blender-xray pull request #214
Opened 2019-02-18 09:43 UTC by PavelBlend

Описание проблемы:
https://github.com/PavelBlend/blender-xray/issues/74

2019-02-18 20:21 UTC, igelbox requested changes

2019-02-18 20:21 UTC, igelbox commented on io_scene_xray/fmt_object_imp.py
> +            ik.lim_x_min, ik.lim_x_max = map(math.degrees, reader.getf('ff'))
А зачем вообще импортировать значения в новые свойства?
Давай оставим тут всё как есть (ik_min_x и т.п.), а новые свойства lim_x_max будут типа виртуальные (например как `ctime_str = _gen_time_prop('ctime', description='Creation time')`), т.е. с get (который будет делать `return math.degrees(self.ik_min_x)`) и set (который будет делать `self.ik_min_x = math.radians(value)`). Тогда и старые blend-файлы работать будут и не нужны станут 2 оператора по конвертации, т.к. она будет автоматом на лету происходить.

2019-02-19 09:58 UTC, PavelBlend commented on io_scene_xray/fmt_object_imp.py
> +            ik.lim_x_min, ik.lim_x_max = map(math.degrees, reader.getf('ff'))
Новые свойства lim_x_min нужны из-за того, что они не влияют на ИК, в отличии от ik_min_x.
ik_min_x мешает анимировать при тех значениях, которые используются для ragdoll.
Нужно, чтобы лимиты XRay имели свои значения, а лимиты ИК свои.
Получается персонаж будет более/менее гибким во время анимации и в ragdoll'е.
Но я думаю, что это не проблема, так как это ведь игра и не будет сильно заметно различие в гибкости.
Если оставить всё, как есть, то при анимировании, придётся перенастраивать почти все лимиты ИК. А это лишняя работа. Например, нужно создать одну анимацию для монстра, и придётся всё перенастраивать ради одной анимации. И после перенастройки модель уже будет вести себя при ragdoll'е по-другому (то есть получается своего рода нежелательный побочный эффект, после анимирования).
Вот пример:
![01](https://user-images.githubusercontent.com/7983249/53006059-875e4200-3445-11e9-9baf-f722491483c1.jpg)
Слева оригинальная анимация, а справа - после применения лимитов. С использованием лимитов ИК невозможно выкрутить так ногу, как в оригинальной анимации.

2019-02-19 23:12 UTC, igelbox commented on io_scene_xray/fmt_object_imp.py
> +            ik.lim_x_min, ik.lim_x_max = map(math.degrees, reader.getf('ff'))
Думаю с [enum-параметром](https://github.com/PavelBlend/blender-xray/issues/74#issuecomment-464773255) должно получиться.

2019-03-06 20:59 UTC, igelbox commented
Проверил. Клёвая штука, особенно отрисовка лимитов.

Единственное что, код отрисовки сложный получился и FPS у меня низкий, если все кости у модельки человека выделить.
Поэтому я сделал фикс - 2d39f26fe2d145e231cca22972bfbd1f538b149a, если норм, то за черрипикай его к себе в ветку.

2019-03-06 20:59 UTC, igelbox approved these changes

2019-03-07 09:31 UTC, merged