Более строгий экспорт
PavelBlend/blender-xray pull request #274
Opened 2019-07-23 10:48 UTC by PavelBlend

Данный pull request решает эту проблему #266

2019-07-24 22:09 UTC, igelbox requested changes

2019-07-24 22:09 UTC, igelbox commented on io_scene_xray/anm/exp.py
> +    file.close()
Если во время `write` произойдёт ошибка, то `close` не вызовется.
Конечно, для аддона это не беда, но вообще, писать так код - моветон.

2019-07-24 22:09 UTC, igelbox commented on io_scene_xray/obj/exp/__init__.py
> +    file.close()
Много повторов одних и тех же действий. Думаю, это сигнал, что нужно их в общую функцию вынести.

2019-07-24 22:09 UTC, igelbox commented on io_scene_xray/obj/exp/main.py
> +        raise utils.AppError('Mesh "{0}" has {1} vertices that are not tied to any exportable bones'.format(
Уже есть код, который по каким-то условиям отбирает группы и вертексы для экспорта (ну и собственно экспортирует их). А тут мы добавляем ещё один код, который тоже, пытается понять, какие группы будут экспортированы.
=> Получается, при изенении логики работы одного кода, придётся не забывать обновлять и другой, что не есть гуд. Ну и теперь мы тратим ресурсы на обход/проверку геометрии.

Что если перенести подсчёт и генерацию ошибки прямо в код экспорта (куда-то рядом с `wr.append((1 + wmap[1], len(wmap[0])))`)? Я думаю, что нормальный - более частый вариант использования аддона - когда геометрия всё же нормальная, т.е. у нас будет оптимистичная стратегия - что есть гуд)

2019-07-24 22:09 UTC, igelbox commented on io_scene_xray/obj/exp/mesh.py
> +        raise utils.AppError('UV-map is required, but not found on the "{0}" object'.format(bpy_obj.name))
Думаю, bpy_obj.name можно и не передавать явно. Лениво проверять, но, думаю, `raise AppError('unsupported motions version', log_props())` должно сработать (можно поискать по коду упоминания `log_props(` для примера). Заодно, в зависимости от ситуации, там могут ещё какие-то полезные свойства подцепиться.
Т.е. идея была, чтобы сообщение об ошибке автоматом включало доступный на данный момент контекст, вместо того, чтобы явно передавать какой-то ограниченный набор атрибутов.

2019-07-24 22:09 UTC, igelbox commented on tests/cases/test_object_export.py
> -        self.assertNotRegex(content, re.compile(bytes(bg_emp.name, 'cp1251')))
Похоже, теперь сы потеряли тест для одного из кейсов. Лучше бы поправить тест так, чтоб он всё-таки экспортировал и проверял, что `exportable = False` работают, как ожидается.

А для ошибки - сделать отдельный тест-кейс.

2019-07-25 17:49 UTC, PavelBlend commented on io_scene_xray/anm/exp.py
> +    file.close()
Что-то я сразу не додумался: надо было with оставить, а вызов функции вынести за пределы блока with, тогда бы файл размером в 0 байт в случае ошибки не создавался бы.

2019-07-25 17:57 UTC, PavelBlend commented on io_scene_xray/obj/exp/main.py
> +        raise utils.AppError('Mesh "{0}" has {1} vertices that are not tied to any exportable bones'.format(
Я эту проверку сделал, так как есть баг репорт: #265 Пользователь может случайно не назначить веса при создании новой модели. Такие меши экспортировать не нужно, так как СДК крашится и будет трудно понять причину этого. Насчёт производительности: я думаю что это не критично, так как динамические модели, имеющие скелет, как правило имеют не более 10 тыс. треугольников. Для статики было бы критично, так как уровни могут быть и в 2 миллиона треугольников.

Та проверка весов, которая была раньше, не диагностировала данную ошибку. А сейчас с помощью этой второй проверки выдаётся предупреждение.

2019-07-25 17:59 UTC, PavelBlend commented on io_scene_xray/obj/exp/mesh.py
> +        raise utils.AppError('UV-map is required, but not found on the "{0}" object'.format(bpy_obj.name))
С логом я пока не сильно разобрался, поэтому сделал так. Попробую переделать.

2019-07-25 18:03 UTC, PavelBlend commented on tests/cases/test_object_export.py
> -        self.assertNotRegex(content, re.compile(bytes(bg_emp.name, 'cp1251')))
Попробую исправить.

2019-08-03 17:06 UTC, PavelBlend commented on io_scene_xray/obj/exp/mesh.py
> +        raise utils.AppError('UV-map is required, but not found on the "{0}" object'.format(bpy_obj.name))
Я сделал (пока не закоммитил) и в итоге при экспорте, чтобы узнать какой объект не имеет UV карты приходится открывать текстовый редактор, так как имя проблемного объекта пишется только туда. Мой вариант с format выводит имя объекта прям в сплывающее окошко с ошибками. И не нужно открывать текстовый редактор. Как лучше сделать?

2019-08-09 21:32 UTC, igelbox commented on io_scene_xray/obj/exp/mesh.py
> +        raise utils.AppError('UV-map is required, but not found on the "{0}" object'.format(bpy_obj.name))
> Как лучше сделать?

Сложно сказать. Мне нравится разделение комплексной фичи на несколько простых, чтобы потом можно было переиспользовать эти простые части в других местах.
Так и тут, за-форматировав параметр в строку - мы не сможет потом его нормально достать и отформатировать по-другому. Я бы попробовал поправить ту штуку, которая триггерит всплывающее окошко с ошибками, чтобы научить её добавлять последний уровень свойств. Может и в других местах ошибки от этого лучше станут..

2019-08-15 00:20 UTC, igelbox commented on io_scene_xray/obj/exp/main.py
> +        raise utils.AppError('Mesh "{0}" has {1} vertices that are not tied to any exportable bones'.format(
> Та проверка весов, которая была раньше, не диагностировала данную ошибку.

Так давай её и поправим. И получится проверка только в 1-м месте и экспорт там же. Случись чего, сразу понятно где искать и править.

_Я тут подумал, может смёржить этот реквест как-есть, чтоб привнести ценность в продукт (а то он сейчас висит, и пользы не приносит).
Я, просто, навряд ли смогу в ближайшее время чем-то тут помочь, т.к. у меня опять - работа-тренажёрка-гараж и далее по циклу_

2019-08-19 20:07 UTC, PavelBlend commented on io_scene_xray/obj/exp/main.py
> +        raise utils.AppError('Mesh "{0}" has {1} vertices that are not tied to any exportable bones'.format(
Хорошо. Я буду сейчас мержить. Так как многие ждут релиза под 2.80. А без этих исправлений релиза не будет. Так как этот пулл решает баги.

2019-08-19 20:12 UTC, merged