ogf import: support GUNSLINGER-like mods
PavelBlend/blender-xray pull request #671
Opened 2023-08-06 20:33 UTC by igelbox

Упрощённо-автоматизированная версия #670

2023-08-07 17:04 UTC, igelbox commented on io_scene_xray/formats/ogf/imp/props.py
> +            log.warn(
Ну раз мы теперь сами за пользователя решаем - значит надо хотя б предупредить

2023-08-07 17:04 UTC, igelbox commented on io_scene_xray/formats/ogf/imp/utility.py
> +        log.debug(err)
Хз, надо ли тут WARNING. Не придумал, какое бу для него человеко-понятное сообщение написать.

2023-08-07 17:04 UTC, igelbox commented on io_scene_xray/rw/lzhuf.py
> +class error(Exception): ...
По аналогии с тем, как сделано в `zlib`

2023-08-08 19:31 UTC, PavelBlend requested changes

2023-08-08 19:31 UTC, PavelBlend commented on io_scene_xray/formats/ogf/imp/utility.py
> +        return { id: data for id, data in chunked_reader }
здесь до и после фигурных скобок пробелы лишние

2023-08-08 19:31 UTC, PavelBlend commented on io_scene_xray/formats/ogf/imp/props.py
> +        except rw.read.PackedReader.Errors as err:
здесь до except можно добавить пустую строку, чтобы выделить в отдельный блок. Верхние строчки же отделены в блоки. Значит и except тоже можно. Я когда перечитывал свой старый код, который вообще без единого промежутка, без пустых строк, понял, что лучше код объединять в небольшие логические группы по ~5 строк. Потом начал делать рефактор и добавлял промежутки. Если в каком-то коде нет пустых строк, значит я до него не дошёл.

2023-08-08 19:31 UTC, PavelBlend commented on io_scene_xray/rw/read.py
> +    Errors = (IndexError,)
После запятой можно пробел поставить. Если бы я писал такой код, то поставил бы. Я не знаю, соответствует этот PEP8, но по-моему в аддоне кортежи с одним элементом я с пробелом писал.

2023-08-08 19:31 UTC, PavelBlend commented on io_scene_xray/rw/read.py
> +                return cid, data[offs:offs + size]
Здесь может пробелы добавить так?:
`data[offs : offs+size]`

По моему более читаемо.

2023-08-08 19:31 UTC, PavelBlend commented on io_scene_xray/formats/ogf/imp/utility.py
> +    def read_chunks(ignore_compression=False):
Может переписать код без локальных функций? В чём их преимущество? Не нужно передавать параметры, которые есть у родительской функции?

Я когда переписывал старый код, старался от них избавиться.

2023-08-08 19:31 UTC, PavelBlend commented on io_scene_xray/rw/lzhuf.py
> +class error(Exception): ...
А что означает многоточие? Это какая-то новая функция? Я о её существовании не знал. Этот код будет работать на старых версиях питона, который в блендере 2.77?

2023-08-08 19:31 UTC, PavelBlend commented on utils/dump_ogf.py
>  import io
Здесь то же, что я писал в #670, заменить на абсолютные импорты

2023-08-08 19:33 UTC, PavelBlend commented
@igelbox можно будет смержить, после изменения стиля кода. Если у тебя будут лучшие идеи, как переписать, то пиши. Я не до конца уверен в том, что мои предложения соответствуют pep8.

2023-08-08 19:44 UTC, PavelBlend requested changes
@igelbox можно будет смержить, после изменения стиля кода. Если у тебя будут лучшие идеи, как переписать, то пиши. Я не до конца уверен в том, что мои предложения соответствуют pep8.

2023-08-08 19:52 UTC, igelbox commented on io_scene_xray/rw/read.py
> +                return cid, data[offs:offs + size]
не, т.к. в этом файле всё в таком стиле, ну и я это скопипастил снизу

2023-08-08 19:53 UTC, igelbox commented on io_scene_xray/formats/ogf/imp/utility.py
> +    def read_chunks(ignore_compression=False):
хз, они не попадают в экспорт этого модуля => сразу понятно где она используется (только в этой функции)

2023-08-08 19:53 UTC, igelbox commented on io_scene_xray/formats/ogf/imp/utility.py
> +    def read_chunks(ignore_compression=False):
если скажешь "надо" - я поправлю

2023-08-08 19:55 UTC, igelbox commented on io_scene_xray/rw/lzhuf.py
> +class error(Exception): ...
Так я ж написал) - https://github.com/PavelBlend/blender-xray/pull/671#discussion_r1285259863

Ну, тесты проходят - значит работает.

2023-08-08 19:57 UTC, igelbox commented on utils/dump_ogf.py
>  import io
Я там не виду такого коммента. Искал по "импорт" и по "абс".

А как это сделать? Можно пример?

2023-08-08 20:02 UTC, igelbox commented on utils/dump_ogf.py
>  import io
Нашёл)

2023-08-08 20:03 UTC, igelbox commented
@PavelBlend, да я хз как по PEP8 правильно `¯\\\_(ツ)\_/¯`
Поправил. Глянь, пожалуйста.

2023-08-08 20:29 UTC, igelbox commented
По поводу https://github.com/PavelBlend/blender-xray/pull/670#issuecomment-1670206373:
> gamedata\meshes\dynamics\weapons\wpn_hand\wpn_hand_01.ogf
gamedata\meshes\dynamics\weapons\wpn_hand\wpn_hand_exo_freedom.ogf
gamedata\meshes\dynamics\weapons\wpn_hand\wpn_hand_default.ogf

Впрочем, там есть и нормальные чанки. Из хреновых - только:
```
Unknown OGF  Chunk: 152 (0 bytes)
Unknown OGF  Chunk: 153 (0 bytes)
Unknown OGF  Chunk: 154 (0 bytes)
Unknown OGF  Chunk: 134217784 (266 bytes)
Unknown OGF  Chunk: 1801680198 (0 bytes)
```
но их нет в [исходниках](https://github.com/gunslingermod/GunsXRay/blob/4fd762f6f95c75aba1e4dbb84282e0112fcc819c/src/xrCore/FMesh.hpp#L34) => это похоже просто мусор

2023-08-08 20:33 UTC, PavelBlend commented on io_scene_xray/rw/read.py
> +                return cid, data[offs:offs + size]
это наверное старый код из 2014-2018 годов. Может тогда потом переписать весь код в этом модуле? Просто я не понимаю, зачем выделять пробелом операции, если лучше выделить пробелами начало и конец среза. Вот мой код, который я с нуля писал:
https://github.com/PavelBlend/blender-xray/blob/ca07c2846ff7bd86813c55d94da1d8dfe8d609ce/io_scene_xray/formats/level/exp/geom.py#L83

2023-08-08 20:35 UTC, PavelBlend commented on io_scene_xray/formats/ogf/imp/utility.py
> +    def read_chunks(ignore_compression=False):
для меня такие функции выглядят "уродливо". Это наверное субъективная причина. Я хочу, чтобы код был проще, прямолинейнее, без вложенностей и т. д., чтобы его легче было поддерживать.

2023-08-08 20:37 UTC, PavelBlend commented on io_scene_xray/rw/lzhuf.py
> +class error(Exception): ...
У меня твой коммент вчера сразу не появился почему-то. А когда обновил страницу, он появился, но это было после того, как написал свой. Я когда нагуглил, что это, то вспомнил, что это Ellipsis, который я никогда не использовал и вообще, не понимаю, кто и когда его использует. Может здесь для простоты написать pass?

2023-08-08 20:41 UTC, PavelBlend commented
> Поправил. Глянь, пожалуйста.

сейчас посмотрю. Но я там ещё хотелок дописал, про Ellipsis и т. д.

2023-08-08 20:45 UTC, igelbox commented on utils/dump_ogf.py
>  import io
А, не, всё-таки не работает)
Нужен пример, как поправить можно.

2023-08-08 20:53 UTC, PavelBlend commented on utils/dump_ogf.py
>  import io
а если написать так?:
```python
import io_scene_xray

io_scene_xray.rw.read.ChunkedReader    # и так использовать
```

Если будут ошибки, то пока оставить так, как есть.

Я создавал новый файл с ChunkedReader `utils\xray_io.py`, так как в какой-то момент устал синхронизировать код в аддоне и утилитах. Этот модуль проще, работает медленнее, но выполняет свои функции. Для дампа его можно использовать. Это в аддоне нужно писать кучу проверок, Fast методов... И когда в утилитах есть свой reader, то утилиты не зависят от того, что переписывается в аддоне.

2023-08-08 20:56 UTC, igelbox commented on io_scene_xray/rw/read.py
> +                return cid, data[offs:offs + size]
Я обычно сопротивляюсь деланию нескольких вещей в рамках одного PR-а, т.к. больше пространства для возникновения ошибки/опечатки.
Сейчас код консистентен с тем, что в модуле написано. Не вижу проблем в том, чтоб порефачить этот модуль потом.

Кстати, про OMF - я б тоже потом сделал, т.к. правка OGF: 1 - полезна, 2 - не несёт вреда ни кодовой базе, ни рантайму.

2023-08-08 20:58 UTC, PavelBlend commented on io_scene_xray/rw/read.py
> +                return cid, data[offs:offs + size]
Можно и потом. Главное не забыть. Может issue создать.

2023-08-08 21:02 UTC, igelbox commented on io_scene_xray/rw/read.py
> +                return cid, data[offs:offs + size]
> Может issue создать

Ну уж точно не мне), т.к. мне и такой код норм.

2023-08-08 21:03 UTC, igelbox commented on io_scene_xray/formats/ogf/imp/utility.py
> +    def read_chunks(ignore_compression=False):
Оки, поправил

2023-08-08 21:12 UTC, igelbox commented on utils/dump_ogf.py
>  import io
Короч, я вернул, как у меня было.
Если не норм - давай я тогда лучше вообще откачу правки этого файла, а то он до этого PR не работал, а теперь блочит фичу.

2023-08-08 21:16 UTC, PavelBlend approved these changes
Мержим?

2023-08-08 21:16 UTC, PavelBlend commented on utils/dump_ogf.py
>  import io
А здесь так всё и остаётся? Или ты правишь? Я думаю, можно мержить, если всё остаётся.

2023-08-08 21:16 UTC, PavelBlend commented on utils/dump_ogf.py
>  import io
Пусть остаётся этот, а не старый вариант. Он сейчас хоть работает.

2023-08-08 21:19 UTC, igelbox commented
> Мержим?

Hell yeah!

2023-08-08 21:20 UTC, merged